---
- name: Detach Datacenter
  docker_exec: 
    command: '/bin/bash -c "export OPENMANO_TENANT=osm; openmano datacenter-detach {{dc_name}}"'
    name: osm-ro
  register: step

- fail:
    msg: tenant.result
  when: "'Connection error' in step.result"

- name: Remove Datacenter
  docker_exec: 
    command: '/bin/bash -c "export OPENMANO_TENANT=osm; openmano datacenter-delete -f {{dc_name}}"'
    name: osm-ro

- name: Remove Tenant
  docker_exec: 
    command: '/bin/bash -c "export OPENMANO_TENANT=osm; openmano tenant-delete -f osm"'
    name: osm-ro

- name: Add Tenant
  docker_exec: 
    command: 'openmano tenant-create osm'
    name: osm-ro
  register: tenant

- fail:
    msg: tenant.result
  when: "'already in use' in tenant.result"

- name: export RO info
  set_fact:
    ro_tenant_id: "{{ tenant.result.split(' ')[0] }}"

- debug:
    msg: "Add tenant output: {{ro_tenant_id}}"

- name: Add Openstack
  docker_exec: 
    command: "/bin/bash -c \"export OPENMANO_TENANT=osm; openmano datacenter-create --type openstack --description 'OpenStack Datacenter' --config='{use_floating_ip: true}' openstack {{os_auth_url}}\""
    name: osm-ro
  register: cmd_result

- debug:
    msg: "datacenter-create: {{cmd_result.result}}"

- fail:
    msg: cmd_result.result
  when: "'already in use' in cmd_result.result"

- name: Attach Openstack
  docker_exec: 
    command: '/bin/bash -c "export OPENMANO_TENANT=osm; openmano datacenter-attach {{dc_name}} --user={{os_user}} --password={{os_password}} --vim-tenant-name={{os_tenant_name}}"'
    name: osm-ro
  register: cmd_result

- debug:
    msg: "datacenter-attach: {{cmd_result.result}}"

- fail:
    msg: cmd_result.result
  when: "'{{dc_name}}' not in cmd_result.result"

- name: Read networks
  docker_exec: 
    command: '/bin/bash -c "export OPENMANO_TENANT=osm; export OPENMANO_DATACENTER={{dc_name}}; openmano datacenter-netmap-import --force"'
    name: osm-ro
