---
- name: Install OSM-RO
  docker_container:
    name: osm-ro
    image: 'datelco/osm-ro:v1.1'
    state: started
    pull: true
    restart_policy: always
    env:
        DB_NAME: "{{db_name}}"
        DB_USER: "{{db_user}}"
        DB_PSWD: "{{db_pswd}}"
        DB_HOST: "{{db_host}}"
        DB_PORT: "{{db_port}}"
    dns_search_domains:
      - "{{dns_domain}}"
    dns_servers:
      - "{{dns_server}}"
    ports:
      - "9090:9090"
    volumes:
      - "/var/log/osm/openmano/logs:/opt/openmano/logs"

- include: configure.yml
