- name: Create host VNFM host
  hosts: osm-vnfm
  connection: local
  gather_facts: false
  roles:
    - role: machine
      server_name: osm-vnfm
      server_groups: osm-vnfm 

- name: Setup VNFM software
  hosts: osm-vnfm
  pre_tasks:
    - debug:
        msg: "MTU: {{net_mtu | default('Not specified')}}"
  post_tasks:
    - set_fact:
        private_v4: "{{ hostvars['osm-vnfm']['server_private_v4'] }}"
        public_v4: "{{ hostvars['osm-vnfm']['server_public_v4'] }}"
  roles:
    - docker
    - role: osm-ro-db
      become: true
    - role: osm-ro
      become: true
      os_auth_url: "{{ lookup('env','OS_AUTH_URL') }}"
      os_tenant_name: "{{ lookup('env','OS_TENANT_NAME') }}"
      os_user: "{{ lookup('env','OS_USERNAME') }}"
      os_password: "{{ lookup('env','OS_PASSWORD') }}"
      db_host: "{{ hostvars['osm-vnfm']['server_private_v4'] }}"

- name: Create host RIFT.IO host
  hosts: osm-so
  connection: local
  gather_facts: false
  roles:
    - role: machine
      server_name: osm-so
      server_groups: osm-so

- name: Setup rift.io software
  hosts: osm-so
  post_tasks:
    - set_fact:
        private_v4: "{{ hostvars['osm-so']['server_private_v4'] }}"
        public_v4: "{{ hostvars['osm-so']['server_public_v4'] }}"
  roles:
    - docker
    - role: osm-so
      become: true 
      ro_server: "{{ hostvars['osm-vnfm']['private_v4'] }}"
      ro_tenant_id: "{{ hostvars['osm-vnfm']['ro_tenant_id'] }}"
    - role: osm-ui
      become: true
      host_port: 8443
      api_server: "{{hostvars['osm-so']['server_private_v4']}}"