---
- name: Install OSM-VCA
  docker_container:
    name: osm-vca
    image: 'datelco/osm-vca:v1.1'
    state: started
    pull: true
    restart_policy: always
    dns_search_domains:
      - "{{dns_domain}}"
    dns_servers:
      - "{{dns_server}}"
    ports:
      - "17070:17070"
      - "443:443"
    env:
        NET_MTU: "{{net_mtu}}"
    volumes:
      - "/var/run/dbus:/var/run/dbus"
      - "/run/systemd:/run/systemd"
      - "/usr/bin/systemctl:/usr/bin/systemctl"
      - "/etc/systemd/system:/etc/systemd/system"
      - "/var/lib/lxd/:/var/lib/lxd/"
      - "/etc/default/lxd-bridge:/etc/default/lxd-bridge"

- name: Wait for Juju
  uri:
    url: "https://127.0.0.1:17070"
    status_code: 200
    validate_certs: no
    timeout: 10
  register: result
  until: result.status == 200
  retries: 30
  delay: 5

- name: Read juju settings
  docker_exec: 
    command: "/bin/bash -c \"juju show-controller osm --show-password | grep password | awk '{print $2}'\""
    name: osm-vca
  register: juju_info

- name: Export credentials
  set_fact:
    vca_user: "admin"
    vca_password: "{{ juju_info.result }}"
