---
- name: "Launch an instance for {{server_name}}"
  register: server_vm
  os_server:
    state: present
    name: "{{server_name}}"
    image: "{{ubuntu_image}}"
    key_name: "{{key_name}}"
    timeout: 200
    flavor: "{{flavor}}"
    auto_floating_ip: yes
    network: "{{network}}"
    security_groups: "{{security_groups}}"
    wait: true
    meta:
      hostname: "{{server_name}}"
      group: "{{server_groups}}"

- name: Waiting for server to come back
  wait_for:
    host: "{{ server_vm.server.public_v4 }}"
    port: "{{ ansible_port | default(22) }}"
    state: started

- name: Install python
  command: >
    ssh -oBatchMode=yes -oStrictHostKeyChecking=no
    ubuntu@{{server_vm.server.public_v4}} "sudo apt update && sudo apt install -y python"
  register: result
  until: result|success
  retries: 3
  delay: 10
  when: ansible_ssh_private_key_file is undefined

- name: Install python
  command: >
    ssh -i {{ansible_ssh_private_key_file}} -oBatchMode=yes -oStrictHostKeyChecking=no
    ubuntu@{{server_vm.server.public_v4}} "sudo apt update && sudo apt install -y python"
  register: result
  until: result|success
  retries: 3
  delay: 10
  when: ansible_ssh_private_key_file is defined

- name: Add Ubuntu Instance to Inventory
  add_host: name={{server_name}} groups={{server_groups}}
            ansible_ssh_host={{ server_vm.server.public_v4 }}
            ansible_ssh_user=ubuntu

- name: export server info
  set_fact:
    server_vm: "{{ server_vm.server }}"
    server_private_v4: "{{ server_vm.server.private_v4 }}"
    server_public_v4: "{{ server_vm.server.public_v4 }}"
