---
- name: Install OSM-UI
  docker_container:
    name: osm-ui
    image: 'datelco/osm-ui:v1.1'
    state: started
    pull: true
    restart_policy: always
    dns_search_domains:
      - "{{dns_domain}}"
    dns_servers:
      - "{{dns_server}}"
    ports:
      - "{{host_port}}:8443"
    env:
        API_SERVER: "{{api_server}}"
    volumes:
      - "/var/data-rift/composer-logos:/usr/src/UI/skyquake/plugins/composer/public/assets/logos"